// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpjvNcxfXof7IOSy5yumRI3jXHk17jTpE',
    appId: '1:840891755408:web:020e133d68596b01862115',
    messagingSenderId: '840891755408',
    projectId: 'class-activity-12-637d9',
    authDomain: 'class-activity-12-637d9.firebaseapp.com',
    storageBucket: 'class-activity-12-637d9.firebasestorage.app',
    measurementId: 'G-WJ1B8D4BP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGO2s0FYhIq59dbx9qcMAGtiWQirVEWSA',
    appId: '1:840891755408:android:091b5c978a87bb2f862115',
    messagingSenderId: '840891755408',
    projectId: 'class-activity-12-637d9',
    storageBucket: 'class-activity-12-637d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8NFNTM_f48udONS9wgOpSDMFMguMCcuc',
    appId: '1:840891755408:ios:df6d489da94ed280862115',
    messagingSenderId: '840891755408',
    projectId: 'class-activity-12-637d9',
    storageBucket: 'class-activity-12-637d9.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8NFNTM_f48udONS9wgOpSDMFMguMCcuc',
    appId: '1:840891755408:ios:df6d489da94ed280862115',
    messagingSenderId: '840891755408',
    projectId: 'class-activity-12-637d9',
    storageBucket: 'class-activity-12-637d9.firebasestorage.app',
    iosBundleId: 'com.example.classActivity12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpjvNcxfXof7IOSy5yumRI3jXHk17jTpE',
    appId: '1:840891755408:web:65a18a845e781c9f862115',
    messagingSenderId: '840891755408',
    projectId: 'class-activity-12-637d9',
    authDomain: 'class-activity-12-637d9.firebaseapp.com',
    storageBucket: 'class-activity-12-637d9.firebasestorage.app',
    measurementId: 'G-PCZG9QE3YN',
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Firebase App',
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Firebase Initialized'),
        ),
        body: const Center(
          child: Text('Firebase App is Running'),
        ),
      ),
    );
  }
}
