// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmSzSXoqwBXHzRAdciKhRiqFOO5SmLBEg',
    appId: '1:283633335733:web:580710fb57239ee6c5edfc',
    messagingSenderId: '283633335733',
    projectId: 'group-2-weatherly',
    authDomain: 'group-2-weatherly.firebaseapp.com',
    storageBucket: 'group-2-weatherly.firebasestorage.app',
    measurementId: 'G-Z3H731YS93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi9Jq6lanz-vMtRiCvSBJxD3ThaSOOz-s',
    appId: '1:283633335733:android:a974255750c5a52fc5edfc',
    messagingSenderId: '283633335733',
    projectId: 'group-2-weatherly',
    storageBucket: 'group-2-weatherly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTHlN-wRCUiF8pHjTimyzFpfijHr9BVtU',
    appId: '1:283633335733:ios:851379db604be31ec5edfc',
    messagingSenderId: '283633335733',
    projectId: 'group-2-weatherly',
    storageBucket: 'group-2-weatherly.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTHlN-wRCUiF8pHjTimyzFpfijHr9BVtU',
    appId: '1:283633335733:ios:851379db604be31ec5edfc',
    messagingSenderId: '283633335733',
    projectId: 'group-2-weatherly',
    storageBucket: 'group-2-weatherly.firebasestorage.app',
    iosBundleId: 'com.example.weatherly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmSzSXoqwBXHzRAdciKhRiqFOO5SmLBEg',
    appId: '1:283633335733:web:18d07e4b93690adac5edfc',
    messagingSenderId: '283633335733',
    projectId: 'group-2-weatherly',
    authDomain: 'group-2-weatherly.firebaseapp.com',
    storageBucket: 'group-2-weatherly.firebasestorage.app',
    measurementId: 'G-Z3KMFKRQE6',
  );
}
