// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsB7EQ2dEqyJPqaj3LMd-OUlanDwNTY7s',
    appId: '1:35922875489:web:5201b8b1714cab97e34620',
    messagingSenderId: '35922875489',
    projectId: 'fir-intro-11859',
    authDomain: 'fir-intro-11859.firebaseapp.com',
    storageBucket: 'fir-intro-11859.firebasestorage.app',
    measurementId: 'G-RKY1VQBC8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjYXGReaRiRFolQXQ7oFxYY-mrweuGo74',
    appId: '1:35922875489:android:3eff5530afcd6194e34620',
    messagingSenderId: '35922875489',
    projectId: 'fir-intro-11859',
    storageBucket: 'fir-intro-11859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiFivc-KwPrZvSQUTB1rm3hVIRP7Fl8k',
    appId: '1:35922875489:ios:a374654f9a18b2c3e34620',
    messagingSenderId: '35922875489',
    projectId: 'fir-intro-11859',
    storageBucket: 'fir-intro-11859.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMiFivc-KwPrZvSQUTB1rm3hVIRP7Fl8k',
    appId: '1:35922875489:ios:a374654f9a18b2c3e34620',
    messagingSenderId: '35922875489',
    projectId: 'fir-intro-11859',
    storageBucket: 'fir-intro-11859.firebasestorage.app',
    iosBundleId: 'com.example.firebaseIntro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsB7EQ2dEqyJPqaj3LMd-OUlanDwNTY7s',
    appId: '1:35922875489:web:b778eda8f6274346e34620',
    messagingSenderId: '35922875489',
    projectId: 'fir-intro-11859',
    authDomain: 'fir-intro-11859.firebaseapp.com',
    storageBucket: 'fir-intro-11859.firebasestorage.app',
    measurementId: 'G-HSE2532MWL',
  );

}