name: class_activity_09
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite: ^2.4.0
  path_provider: ^2.1.4
  path: ^1.9.0

flutter:
  uses-material-design: true
