// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_0OGYcyzKvGkFmRokJrCfoCoOg6H1-8',
    appId: '1:222273734663:web:f737221ba34bdaf3a8c2a2',
    messagingSenderId: '222273734663',
    projectId: 'classwork8-9a498',
    authDomain: 'classwork8-9a498.firebaseapp.com',
    storageBucket: 'classwork8-9a498.firebasestorage.app',
    measurementId: 'G-XFRCDRNWYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLpRm-Jwj--vn3w_LUEZjIAJXtooqDOU',
    appId: '1:222273734663:android:82ba309e0b042fd8a8c2a2',
    messagingSenderId: '222273734663',
    projectId: 'classwork8-9a498',
    storageBucket: 'classwork8-9a498.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR1MBZK2Zt2FgAMn4srNW1_QAjpKT68DI',
    appId: '1:222273734663:ios:a7c28df662346fa3a8c2a2',
    messagingSenderId: '222273734663',
    projectId: 'classwork8-9a498',
    storageBucket: 'classwork8-9a498.firebasestorage.app',
    iosBundleId: 'com.example.classwork8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR1MBZK2Zt2FgAMn4srNW1_QAjpKT68DI',
    appId: '1:222273734663:ios:a7c28df662346fa3a8c2a2',
    messagingSenderId: '222273734663',
    projectId: 'classwork8-9a498',
    storageBucket: 'classwork8-9a498.firebasestorage.app',
    iosBundleId: 'com.example.classwork8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZ_0OGYcyzKvGkFmRokJrCfoCoOg6H1-8',
    appId: '1:222273734663:web:e3a86237da0020a4a8c2a2',
    messagingSenderId: '222273734663',
    projectId: 'classwork8-9a498',
    authDomain: 'classwork8-9a498.firebaseapp.com',
    storageBucket: 'classwork8-9a498.firebasestorage.app',
    measurementId: 'G-H4MD0SV4QP',
  );
}
