// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPZtbr5Dvs_Na3ZLaStuXYN_simQiEXL4',
    appId: '1:408031864276:web:5eb9cfb533cd91220ca241',
    messagingSenderId: '408031864276',
    projectId: 'class-activity-14-9f742',
    authDomain: 'class-activity-14-9f742.firebaseapp.com',
    storageBucket: 'class-activity-14-9f742.firebasestorage.app',
    measurementId: 'G-5XG4EVYCDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqnUVIW40nWq0gb0LosWcYp9dExtBDws',
    appId: '1:408031864276:android:adf6452ab79b3f580ca241',
    messagingSenderId: '408031864276',
    projectId: 'class-activity-14-9f742',
    storageBucket: 'class-activity-14-9f742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa1QUWc0txVElrO38ETssE1r__IYVrwGQ',
    appId: '1:408031864276:ios:4bf4f1f9e80afb970ca241',
    messagingSenderId: '408031864276',
    projectId: 'class-activity-14-9f742',
    storageBucket: 'class-activity-14-9f742.firebasestorage.app',
    iosBundleId: 'com.example.classActivity14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa1QUWc0txVElrO38ETssE1r__IYVrwGQ',
    appId: '1:408031864276:ios:4bf4f1f9e80afb970ca241',
    messagingSenderId: '408031864276',
    projectId: 'class-activity-14-9f742',
    storageBucket: 'class-activity-14-9f742.firebasestorage.app',
    iosBundleId: 'com.example.classActivity14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPZtbr5Dvs_Na3ZLaStuXYN_simQiEXL4',
    appId: '1:408031864276:web:d13745426201eafb0ca241',
    messagingSenderId: '408031864276',
    projectId: 'class-activity-14-9f742',
    authDomain: 'class-activity-14-9f742.firebaseapp.com',
    storageBucket: 'class-activity-14-9f742.firebasestorage.app',
    measurementId: 'G-RCND7XJB33',
  );
}
