name: weatherly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
<<<<<<< HEAD
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  geolocator: ^13.0.2
  image_picker: ^1.1.2
=======
  firebase_messaging: ^15.1.5
  http: ^1.2.2
  provider: ^6.1.2
  google_maps_flutter: ^2.10.0
>>>>>>> main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
