// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnoQdg9jlo-Froo7QmL51Qv-zI_j4W0Nw',
    appId: '1:547313033930:web:cb8265d041e7ba99b2ca33',
    messagingSenderId: '547313033930',
    projectId: 'class-work-6-7b1e8',
    authDomain: 'class-work-6-7b1e8.firebaseapp.com',
    storageBucket: 'class-work-6-7b1e8.firebasestorage.app',
    measurementId: 'G-KVSD8DKEZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZfhjeZ0U72l8aR_9YrP9fWoArWsgxtE',
    appId: '1:547313033930:android:5e5620d79dbb0bc7b2ca33',
    messagingSenderId: '547313033930',
    projectId: 'class-work-6-7b1e8',
    storageBucket: 'class-work-6-7b1e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ_KJ4dUZkhSPAi2eAW3sIF11gCek2_gc',
    appId: '1:547313033930:ios:f272a800e62d9077b2ca33',
    messagingSenderId: '547313033930',
    projectId: 'class-work-6-7b1e8',
    storageBucket: 'class-work-6-7b1e8.firebasestorage.app',
    iosBundleId: 'com.example.classWork6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ_KJ4dUZkhSPAi2eAW3sIF11gCek2_gc',
    appId: '1:547313033930:ios:f272a800e62d9077b2ca33',
    messagingSenderId: '547313033930',
    projectId: 'class-work-6-7b1e8',
    storageBucket: 'class-work-6-7b1e8.firebasestorage.app',
    iosBundleId: 'com.example.classWork6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnoQdg9jlo-Froo7QmL51Qv-zI_j4W0Nw',
    appId: '1:547313033930:web:6f96c5c866b07e37b2ca33',
    messagingSenderId: '547313033930',
    projectId: 'class-work-6-7b1e8',
    authDomain: 'class-work-6-7b1e8.firebaseapp.com',
    storageBucket: 'class-work-6-7b1e8.firebasestorage.app',
    measurementId: 'G-0MQVX48YKZ',
  );
}
