// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu4RjJ2CankJW1PuJ4lYVthccr07ejkR0',
    appId: '1:514830865856:web:8eaa90733b47a544b86425',
    messagingSenderId: '514830865856',
    projectId: 'weather-app-9adfe',
    authDomain: 'weather-app-9adfe.firebaseapp.com',
    storageBucket: 'weather-app-9adfe.firebasestorage.app',
    measurementId: 'G-VEMHKN44FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0F42QwJVtkMwmizDE8fQn9yd4i_fST4',
    appId: '1:514830865856:android:b79b5c12de04efb5b86425',
    messagingSenderId: '514830865856',
    projectId: 'weather-app-9adfe',
    storageBucket: 'weather-app-9adfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7tXWgthPVxkuUxQ1erRHdqILOK-TFbY',
    appId: '1:514830865856:ios:4ee428f850947bf0b86425',
    messagingSenderId: '514830865856',
    projectId: 'weather-app-9adfe',
    storageBucket: 'weather-app-9adfe.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppGroup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7tXWgthPVxkuUxQ1erRHdqILOK-TFbY',
    appId: '1:514830865856:ios:4ee428f850947bf0b86425',
    messagingSenderId: '514830865856',
    projectId: 'weather-app-9adfe',
    storageBucket: 'weather-app-9adfe.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppGroup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu4RjJ2CankJW1PuJ4lYVthccr07ejkR0',
    appId: '1:514830865856:web:925d76db2b9b837bb86425',
    messagingSenderId: '514830865856',
    projectId: 'weather-app-9adfe',
    authDomain: 'weather-app-9adfe.firebaseapp.com',
    storageBucket: 'weather-app-9adfe.firebasestorage.app',
    measurementId: 'G-RF93EH57L4',
  );
}
