name: firebase_intro
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
<<<<<<< HEAD
  sdk: ^3.5.3
=======
  sdk: ^3.5.4
>>>>>>> dab09e34f7062fb8e482d276596dfff01d68b8c0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
